// Generated steps data for Helping Hands MB City Planning Lessons
const lessonSteps = [
    {
        "title": "1. Welcome & City Limits",
        "content": "<p>Welcome, future urban designers and architects! Welcome to the Helping Hands MB City Planning Workshop. Today, you are going to learn how real planners design communities where people can live, work, and play together safely and happily.</p>\n<p>Every great city has a defined boundary that separates the busy streets and houses from the surrounding countryside or forests. This boundary is called the <strong>city limits</strong>. It shows exactly where the city's services, like fire trucks and clean drinking water pipes, are provided.</p>\n<p>To begin your design, select the <strong>City Limits</strong> tool from the left menu on the Map Drawer. Click and drag on the grid to paint a custom shape for your city! It can be a circle, a rectangle, or even a winding shape near a river.</p>\n<p><strong>Discussion Question:</strong> Why do you think a city needs to have official borders or <strong>city limits</strong>? Think about how we decide where to build city parks or send school buses!</p>\n<p>Once you have painted your city limits, click \"Next Step\" to continue.</p>"
    },
    {
        "title": "2. Neighborhoods & Zoning",
        "content": "<p>Now that your city has a boundary, it's time to decide where things should go. In urban planning, this is called <strong>zoning</strong>. Zoning is a set of rules that divides land into different zones so that noisy factories aren't built right next to quiet homes!</p>\n<p>Today, we will focus on two major types of zoning: 1. <strong>Residential</strong> zones, which form our <strong>neighborhood</strong> blocks. This is where people build houses and apartments to live with their families. 2. <strong>Commercial</strong> zones, which are meant for businesses and shops. This is where people work, buy groceries, and go shopping!</p>\n<p>Select the <strong>Neighborhood</strong> tool and paint a few blocks of homes inside your city limits. Then, select the <strong>Business</strong> tool and paint a separate block for shops nearby!</p>\n<p><strong>Discussion Question:</strong> Why is it a good idea to separate our quiet <strong>residential</strong> homes from loud, busy <strong>commercial</strong> shops, but still keep them close enough to visit easily?</p>\n<p>Once you have painted your homes and businesses, click \"Next Step\" to continue.</p>"
    },
    {
        "title": "3. Connecting Your City",
        "content": "<p>A great city isn't just buildings—it needs systems to help people move around and enjoy nature! All of these physical systems, like roads and tracks, are called <strong>infrastructure</strong>.</p>\n<p>To make your city happy and sustainable, you need to add: - <strong>Transit</strong> systems: Select the <strong>Road</strong> or <strong>Train Track</strong> tools to build pathways connecting your homes to your shops. This helps people make their daily <strong>commute</strong> to school or work! - <strong>Green space</strong>: Select the <strong>Park / Trees</strong> tool to paint parks and forests near your homes. Parks clean our air, provide places to play, and make our cities beautiful!</p>\n<p>Select the <strong>Road</strong>, <strong>Train Track</strong>, and <strong>Park / Trees</strong> tools and paint pathways and green areas on your map. Make sure your residents can easily travel between their homes and shops!</p>\n<p><strong>Discussion Question:</strong> How does having lots of <strong>green space</strong> and good <strong>transit</strong> lines help make a city a healthier and happier place to live?</p>\n<p>Congratulations! You have designed your very first smart city. Talk with your teacher or classmates about your custom city layout!</p>"
    }
];
